# SITE CONFIGURATION
baseurl: ""
url: "https://www.nowcloud.co.uk"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: |+
      nowcloud.co.uk | 
      A blog by Kamil Lygas
  avatar: assets/img/avatar.jpg
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "Kamil Lygas" # used by search engines

  # Header and footer text
  header_text: 
  header_text_feature_image: 
  footer_text: >
   Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/rohanchandra/type-theme">Type Theme</a>

  # Icons
  rss: true
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "czujto"
  gitter:
  google_plus:
  instagram:
  linkedin: "https://www.linkedin.com/in/kamil-lygas-5804528/"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "czujto"
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-45703203-2
  disqus_shortname: czujtoczujto
  katex: true # Enable if using math markup
  search: false # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "Kamil Lygas/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
exclude:
  - Gemfile
  - Gemfile.lock
